format_version: 2
pipelines:
  pipeline_spring_boot_demo:
    group: springbootdemoapp
    materials:
      backend:
        git: https://github.com/pravatsb1/spring-boot-h2-war-tomcat.git
        branch: develop
    stages:
      - Build_Demo_Project_Stage:
          clean_workspace: true
          jobs:
            build_task:
              tasks:
                - exec:
                    run_if: passed
                    command: mvn
                    arguments:
                    - package
              resources:
                - linux
                - spring
      - Start_Tomcat_Stage:
          clean_workspace: true
          jobs:
            start_tomcat_task:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - start_tomcat.sh
                    - /opt/tomcat-10.0.8
              resources:
                - linux
                - spring
      - Deploy_Project_Stage:
          clean_workspace: true
          jobs:
            deploy_project_task:
              tasks:
                - exec:
                    run_if: passed
                    command: mvn
                    arguments:
                    - -version
                    #- tomcat10:deploy
              resources:
                - linux
                - spring      
